-- 코드를 입력하세요
SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) AS 전화번호
FROM 
    USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_USER AS UGU
    ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGU.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)
GROUP BY 
    UGU.USER_ID
ORDER BY UGU.USER_ID DESC