-- 코드를 입력하세요
SELECT
    # *, 
    H.HISTORY_ID,
    CASE 
    WHEN H.CAR_DISCOUNT LIKE '%일 이상' THEN ROUND(C.DAILY_FEE * ((100-P.DISCOUNT_RATE) * 0.01) * (DATEDIFF(H.END_DATE, H.START_DATE) + 1))
    ELSE ROUND(DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE
    END AS FEE
FROM 
    # 각 일수에 맞는 할인타입이 적힌 테이블 
    (
        SELECT *, 
            CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            END AS CAR_DISCOUNT
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE AND H.CAR_DISCOUNT = P.DURATION_TYPE
WHERE
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    H.HISTORY_ID DESC