-- 코드를 입력하세요
SELECT
    # *, 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH,
    I.GENDER, 
    COUNT(DISTINCT(I.USER_ID)) AS USERS
FROM 
    USER_INFO AS I
    JOIN ONLINE_SALE AS O
    ON I.USER_ID = O.USER_ID
WHERE 
    I.GENDER IS NOT NULL
GROUP BY 
    YEAR, 
    MONTH, 
    GENDER
ORDER BY 
    YEAR, 
    MONTH, 
    GENDER