-- 코드를 작성해주세요
SELECT 
    COUNT(ID) AS FISH_COUNT
FROM FISH_INFO AS FI
    INNER JOIN FISH_NAME_INFO AS FNI
        ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.FISH_TYPE IN (SELECT FISH_TYPE
                   FROM FISH_NAME_INFO
                   WHERE FISH_NAME IN ('BASS', 'SNAPPER'))